name: ğŸš€ FTP Deploy
on: [push, workflow_dispatch]
jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Where am I?
        run: ls
      - uses: actions/checkout@v2.1.0
      - name: ğŸ›’ FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server: ${{ secrets.HOST }}
          ftp-username: ${{ secrets.USER }}
          ftp-password: ${{ secrets.PW }}
          local-Dir: 'sportsman_cal'
          remote-Dir: 'public_html\cpgit'
      ##- name: ğŸ“¦ Get LFTP
      ##  run: sudo apt install lftp
      ##- name: ğŸ› ï¸ Configure LFTP
      ##  run: mkdir ~/.lftp && echo "set ssl:verify-certificate false;" >> ~/.lftp/rc
      - name: Where am I now?
        run: ls
      - name: ğŸ”‘ Load Secrets
        run: echo "machine ${{ secrets.HOST }} login ${{ secrets.USER }} password ${{ secrets.PW }}" > ~/.netrc
      - name: ğŸ“„ Upload File
        run: echo "I farted"
        ##run: lftp -e "put -O /public_html/cpgit/ ./README.md" -u ${{ secrets.USER }}:${{ secrets.PW }}@${{ secrets.HOST }}
     ## - name: ğŸ“ Upload Folders
        ##run: lftp -e "mirror --parallel=100 " ${{ secrets.HOST }}
